name: PureEntities-MMC
main: leinne\pureentities\PureEntities
version: 2.0.1
api: 5.0.0

load: STARTUP
authors: ["LeinneSW", "supercrafter333 (MiezeMC)"]
description: Implement all MCBE entities
website: https://github.com/LeinneSW/PureEntities

permissions:
  summon.cmd:
    description: Command permission
    default: op
  mmc.mobs:
    description: Gameplay permission
    default: op